server:
  # 指定该Eureka实例的端口
  port: 8761

eureka:
  instance:
    # 指定该Eureka实例的主机名
    hostname: 10.10.10.77
    preferIpAddress: true
  server:
    # 关闭自我保护机制 不推荐
    # 清理无效的服务节点，清理间隔（单位毫秒，默认是60*1000）
    eviction-interval-timer-in-ms: 10000
  client:
    registerWithEureka: false #false表示不向注册中心注册自己
    fetchRegistry: false #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF
info:
  name: '@project.artifactId@'
  parent: '@project.parent.artifactId@'
  description: '@project.description@'
  version: '@project.version@'

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS